### ISSUE TITLE
Todo: Fix whatever I did to mess up node modules

### ISSUE THREAD

**Issue by LilyMakesThings** [Unsandboxed/scratch-gui#59]
I really screwed something up somewhere but I need to sleep. Putting this here so that I don't forget.

**Comment by veggiecan0419** [comment]
Maybe #61 helps?

**Comment by LilyMakesThings** [comment]
> Maybe #61 helps?

Worth a try lol

**Comment by LilyMakesThings** [comment]
![image](https://github.com/Unsandboxed/scratch-gui/assets/127533508/a3364ea5-e7f5-42f9-a231-57c93da2b9d3)

Thanks for the fix!

**Comment by veggiecan0419** [comment]
> ![image](https://private-user-images.githubusercontent.com/127533508/338802135-a3364ea5-e7f5-42f9-a231-57c93da2b9d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2OTgsIm5iZiI6MTcxODE1OTM5OCwicGF0aCI6Ii8xMjc1MzM1MDgvMzM4ODAyMTM1LWEzMzY0ZWE1LWU3ZjUtNDJmOS1hMjMxLTU3YzkzZGEyYjlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYThhZWVmMDAyMzgwYTFjOWVmMTkyNDBjYzIyNWE4ZTQyNmU1NWYzYTY1MmE4MjA4YzUzMTE3NDMzMDI1MDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y1Z_Th1pMupYBKhneFwiTmG2vgh5lh3q1ATQxYmE3xE)
> 
> Thanks for the fix!

Lol
