### ISSUE TITLE
Visual report for objects is broken

### ISSUE THREAD

**Issue by yuri-kiss** [Unsandboxed/scratch-gui#74]
We know why and when object support is fully done it will be fixed, for now expect to see `{"0": "u","1": "n","2": "d","3": "e","4": "f","5": "i","6": "n","7": "e","8": "d"}` instead of your object in the visual report.
That return value is a way of saying it failed to convert the JSON.
(Note this is not a VM issue as its within the GUIs code, but the issue does lie inside the Cast function)

**Comment by yuri-kiss** [comment]
a temporary fix is being implemented do not worry, but I wont guarantee it will work all the time

**Comment by LilyMakesThings** [comment]
Fixed with https://github.com/Unsandboxed/scratch-vm/issues/55
