### ISSUE TITLE
List Issue

### ISSUE THREAD

**Issue by MasterThomas15** [Unsandboxed/scratch-gui#91]
Moved to https://github.com/Unsandboxed/scratch-parser/issues/3

### Expected Behavior

Load your sb3 that has multiple lists in it perfectly fine

### Actual Behavior

Load your sb3 and get an error message.

### Steps to Reproduce

Step 1. Make 2 lists.

Step 2. Save your project.

Step 3. Load your project.

Step 4. ERROR

### Operating System and Browser

too lazy tto check browser but im on mac

**Comment by yuri-kiss** [comment]
I had the same issue, since this isnt informal enough ill close this and make my own issue

**Comment by yuri-kiss** [comment]
fixed
